package com.socgen.sgs.api.quark.engine.domain.task;
import com.socgen.sgs.api.quark.engine.domain.DataNameValue;
import com.socgen.sgs.api.quark.engine.domain.Run;
import com.socgen.sgs.api.quark.engine.domain.bloc.BlocBase;
import com.socgen.sgs.api.quark.engine.domain.dynamic.report.DMasterPage;
import com.socgen.sgs.api.quark.engine.enums.SubTaskTypeEnum;
import lombok.Getter;
import lombok.Setter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
/** Abstract base class for all task types in a run. */
@Getter
@Setter
public abstract class TaskBase {
    private static final String DEF_NULL_STRING    = " ";
    private static final String DEBUG_INFO_PATTERN = "[%d - %s]";
    private final int    id;
    private final Run    run;
    private String         commentaire;
    private boolean        todo;
    private boolean        toLoad;
    private boolean        allwaysReprocess       = false;
    private String         sourceBlocName;
    private String         destinationBlocName;
    private String         nullString             = DEF_NULL_STRING;
    private SubTaskTypeEnum subTaskType;
    private boolean        inError                = false;
    private DMasterPage    masterPage;
    /** Task properties for page/layout configuration. */
    private final TaskProperties properties = new TaskProperties();
    /** Blocs for value update (NameValue command). Keyed by bloc name. */
    private final Map<String, BlocBase> blocsUpdate = new LinkedHashMap<>();
    /** Blocs for structure/value modification (Modify command). Keyed by bloc name. */
    private final Map<String, BlocBase> blocsModify = new LinkedHashMap<>();
    /** Exception tasks keyed by bloc name. */
    private final Map<String, TaskException> exceptions = new LinkedHashMap<>();
    /** Data generated by this task. */
    private final List<DataNameValue> dataNamesValues = new ArrayList<>();
    protected TaskBase(int id, Run run) {
        this.id         = id;
        this.run        = run;
        this.masterPage = DMasterPage.DEFAULT;
    }
    /** Prepares the task. */
    public abstract void prepare();
    /**
     * Evaluates properties linked to the latest version of the gabarit.
     * Executed between each step before real execution.
     * Override in specific task types.
     */
    public void evaluateInfo() {
        // Re-evaluate the destination bloc's page/layout from the current gabarit XML.
        // Cross-reference: .NET Task_Base.Evaluate_Info().
        if (destinationBlocName != null && !destinationBlocName.isBlank()) {
            properties.setPageNum(getRun().getGabarit().getQxpXml().getPageNum(destinationBlocName));
            properties.setLayoutName(getRun().getGabarit().getQxpXml().getLayoutName(destinationBlocName));
        }
    }
    /**
     * Returns the page ID evaluated from the relative page offset.
     *
     * @param condName     conditional bloc name
     * @param relativePage relative page index
     * @return evaluated page ID
     */
    public int getPageIdFromRelative(String condName, int relativePage) {
        int spreadNum;
        // A conditional bloc, when set, drives the page evaluation; otherwise use the task's own page.
        // Cross-reference: .NET Task_Base.Get_Page_ID_From_Relative().
        if (condName != null && !condName.isBlank()) {
            spreadNum = getRun().getGabarit().getQxpXml().getPageNum(condName);
        } else {
            spreadNum = properties.getPageNum();
        }
        return spreadNum + relativePage;
    }
    /**
     * Returns the spread ID from a given page ID.
     *
     * @param pageId    the page ID
     * @param lagSpread whether spread 1 was deleted (double-page handling)
     * @return the evaluated spread ID
     */
    public int getSpreadIdFromPageId(int pageId, boolean lagSpread) {
        int nbPageBySpread = run.getRunProperties().getNbPageBySpread();
        if (nbPageBySpread == 1) {
            return pageId;
        }
        if (pageId == 1) {
            return 1;
        }
        double val = lagSpread
                ? (double) pageId / nbPageBySpread + 1
                : (double) (pageId + 1) / nbPageBySpread;
        return (int) Math.ceil(val);
    }
    /** Returns the debug info string in format [id - commentaire]. */
    public String getDebugInfo() {
        return String.format(DEBUG_INFO_PATTERN, this.id, this.commentaire);
    }
    /** Resets blocs and data generated during a previous processing step. */
    public void resetProcess() {
        blocsUpdate.clear();
        blocsModify.clear();
        dataNamesValues.clear();
    }
    /** Whether this task makes direct calls to QuarkXPress Server. Override if needed. */
    public boolean isDirectCall() {
        return false;
    }
    /** Whether this task is in degraded mode. Override in specific task types. */
    public boolean isModeDegrade() {
        return false;
    }
}
